name: Release (GitHub/PyPI) and Deploy Docs

on:
  workflow_dispatch:
  push:
    tags:
      - '*'  # Trigger on all tags initially, but tag and release privilege are verified in _build-wheel-release-upload.yml

jobs:
  release:
    uses: Billingegroup/release-scripts/.github/workflows/_build-wheel-release-upload.yml@v0
    with:
      project: diffpy.structure
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
